# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Basys3_Master_v2.xdc

# Block Designs: bd/display_block/display_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block || ORIG_REF_NAME==display_block} -quiet] -quiet

# IP: bd/display_block/ip/display_block_clk_wiz_0_0/display_block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_clk_wiz_0_0 || ORIG_REF_NAME==display_block_clk_wiz_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_blk_mem_gen_0_0/display_block_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_blk_mem_gen_0_0 || ORIG_REF_NAME==display_block_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_VGA_output_0_1/display_block_VGA_output_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_VGA_output_0_1 || ORIG_REF_NAME==display_block_VGA_output_0_1} -quiet] -quiet

# IP: bd/display_block/ip/display_block_memory_mapper_0_0/display_block_memory_mapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_memory_mapper_0_0 || ORIG_REF_NAME==display_block_memory_mapper_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_cell_array_ag_wraper_0_0/display_block_cell_array_ag_wraper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_cell_array_ag_wraper_0_0 || ORIG_REF_NAME==display_block_cell_array_ag_wraper_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_length_state_machine_0_0/display_block_length_state_machine_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_length_state_machine_0_0 || ORIG_REF_NAME==display_block_length_state_machine_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_apple_setter_0_0/display_block_apple_setter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_apple_setter_0_0 || ORIG_REF_NAME==display_block_apple_setter_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_snake_increment_0_0/display_block_snake_increment_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_snake_increment_0_0 || ORIG_REF_NAME==display_block_snake_increment_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_direction_decider_0_0/display_block_direction_decider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_direction_decider_0_0 || ORIG_REF_NAME==display_block_direction_decider_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_seven_seg_driver_0_0/display_block_seven_seg_driver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_seven_seg_driver_0_0 || ORIG_REF_NAME==display_block_seven_seg_driver_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_xlconstant_0_0/display_block_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_xlconstant_0_0 || ORIG_REF_NAME==display_block_xlconstant_0_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_xlconstant_1_0/display_block_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_xlconstant_1_0 || ORIG_REF_NAME==display_block_xlconstant_1_0} -quiet] -quiet

# IP: bd/display_block/ip/display_block_xlconstant_1_1/display_block_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_xlconstant_1_1 || ORIG_REF_NAME==display_block_xlconstant_1_1} -quiet] -quiet

# IP: bd/display_block/ip/display_block_xlconstant_1_2/display_block_xlconstant_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_xlconstant_1_2 || ORIG_REF_NAME==display_block_xlconstant_1_2} -quiet] -quiet

# IP: bd/display_block/ip/display_block_xlconstant_1_3/display_block_xlconstant_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_block_xlconstant_1_3 || ORIG_REF_NAME==display_block_xlconstant_1_3} -quiet] -quiet

# XDC: c:/Users/jl972/Desktop/HDL/Snake_V3/Snake.gen/sources_1/bd/display_block/display_block_ooc.xdc
